name: Buildar, assinar e publicar a imagem

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  security-check:
    uses: './.github/workflows/reusable_security_check.yaml'

  release:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: security-check
    if: ${{ success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        id: build-and-push
        with:
          push: true
          tags: eduardothums/girus:frontend-${{ github.ref_name }}
          build-args: |
            revision=${{ github.sha }}
            version=${{ github.ref_name }}
        env:
          SOURCE_DATE_EPOCH: 0

      - name: Install cosign
        uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2
        with:
          cosign-release: v2.5.0

      - name: Check install!
        run: cosign version

      - name: Sign image
        run: cosign sign --yes --key env://COSIGN_PRIVATE_KEY eduardothums/girus@${{ steps.build-and-push.outputs.digest }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Create release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2

  update_helm:
    runs-on: self-hosted
    needs: release
    if: ${{ success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          repository: EduardoThums-Girus-PICK/helm
          token: ${{ secrets.PAT }}

      - name: Create new branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global commit.gpgsign false
          git checkout -b feat/update-frontend-version-to-${{ github.ref_name }}

      - name: Change frontend image version on values.yaml
        run: sed -i -E "s/eduardothums\/girus:frontend-.*/eduardothums\/girus:frontend-${{ github.ref_name }}/g" charts/girus/values.yaml

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated update by GitHub Actions"

      - name: Push changes
        run: git push origin HEAD

      - name: Create Pull Request using GitHub CLI
        run: |
          gh pr create \
            --title "Update frontend image version to ${{ github.ref_name }}" \
            --body "This PR was automatically created by GitHub Actions" \
            --base main \
            --head $(git branch --show-current)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
