name: Analisar as vulnerabilidades do código e da imagem

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-check:
    uses: './.github/workflows/reusable_security_check.yaml'
